{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: {{ template "ppfc.name" . }}
    chart: {{ template "ppfc.chart" . }}
    component: {{ .Values.ppfc.name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "ppfc.fullname" . }}
rules:
{{ toYaml .Values.rbac.role.rules }}
{{- end }}
