{{- if .Values.mysql.mysqlPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "ppfc.fullname" . }}
  labels:
    app: {{ template "ppfc.name" . }}
    chart: {{ template "ppfc.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  db-password: {{ .Values.mysql.mysqlPassword | b64enc | quote }}
{{- end }}
